-   repo: git@github.com:joblocal/pre-commit-php.git
    sha: 2c2e9147eff52315e176b66155f33c0c90e82378
    hooks:
    -   id: php-cs
        files: \.(php)$
        args:
        - --standard=phpcs.xml -p
    -   id: php-unit
